from home import HomeWindow as Home
from correspondenceWindow import CorrespondenceWindow as Correspondence
from organizationWindow import OrganizationWindow as Organization
from sotrudnikiWindow import SotrudnikiWindow as Sotrudniki